-- MySQL Script generated by MySQL Workbench
-- Wed Feb 17 20:45:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gamehub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gamehub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gamehub` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gamehub` ;

-- -----------------------------------------------------
-- Table `gamehub`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamehub`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `creation_time` TIMESTAMP NULL DEFAULT NULL,
  `last_modified` TIMESTAMP NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_login` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gamehub`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamehub`.`game` (
  `game_id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `creation_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` BIGINT NOT NULL,
  `genre_id` BIGINT NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`game_id`),
  UNIQUE INDEX `game_id_UNIQUE` (`game_id` ASC) VISIBLE,
  INDEX `fk_game_genre1_idx` (`genre_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `gamehub`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 82
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gamehub`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamehub`.`genre` (
  `genre_id` BIGINT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`genre_id`),
  UNIQUE INDEX `genre_id_UNIQUE` (`genre_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gamehub`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamehub`.`hibernate_sequence` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gamehub`.`leaderboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamehub`.`leaderboard` (
  `score` BIGINT NULL DEFAULT NULL,
  `game_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `last_modified` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`game_id`, `user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gamehub`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamehub`.`message` (
  `msg_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `game_id` BIGINT NOT NULL,
  `creation_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `parent_id` BIGINT NULL DEFAULT '-1',
  PRIMARY KEY (`msg_id`),
  UNIQUE INDEX `msg_id_UNIQUE` (`msg_id` ASC) VISIBLE,
  INDEX `fk_message_game1_idx` (`game_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gamehub`.`msg_vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamehub`.`msg_vote` (
  `user_id` BIGINT NOT NULL,
  `did_upvote` BIT(1) NULL DEFAULT NULL,
  `msg_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_id`, `msg_id`),
  INDEX `fk_msg_vote_message1_idx` (`msg_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gamehub`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamehub`.`ratings` (
  `user_id` BIGINT NOT NULL,
  `rating` INT NOT NULL,
  `game_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_id`, `game_id`),
  INDEX `fk_ratings_game1_idx` (`game_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gamehub`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamehub`.`role` (
  `role_id` BIGINT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
